# Generated by Django 4.1 on 2022-09-11 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0001_initial"),
        ("order", "0002_alter_order_options_alter_lineitem_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="item.item",
            ),
        ),
    ]
